version: '3.8'

services:
  addons-api:
    build:
      context: .
      dockerfile: src/Addons.Api/Dockerfile
    container_name: scenery-addons-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - Mongo__ConnectionString=mongodb://mongo:27017
      - Mongo__DatabaseName=sceneryaddons
      - RefreshToken=${REFRESH_TOKEN:-your-secret-refresh-token}
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - addons-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo:latest
    container_name: scenery-addons-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sceneryaddons
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    restart: unless-stopped
    networks:
      - addons-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local

networks:
  addons-network:
    driver: bridge
